# Generated by Django 5.2.7 on 2026-03-11 12:37

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0001_initial'),
        ('payments', '0007_payment_invoice_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('period_start', models.DateField(help_text='Membership period start date (April 1st)')),
                ('period_end', models.DateField(help_text='Membership period end date (March 31st)')),
                ('base_amount', models.DecimalField(decimal_places=2, default=Decimal('150000.00'), max_digits=10)),
                ('previous_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('balance_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('partial', 'Partially Paid'), ('paid', 'Fully Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membership Invoice',
                'verbose_name_plural': 'Membership Invoices',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoicePaymentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_links', to='payments.payment')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_links', to='admin_management.membershipinvoice')),
            ],
            options={
                'verbose_name': 'Invoice Payment Link',
                'verbose_name_plural': 'Invoice Payment Links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='membershipinvoice',
            index=models.Index(fields=['user', 'status'], name='admin_manag_user_id_3f7a42_idx'),
        ),
        migrations.AddIndex(
            model_name='membershipinvoice',
            index=models.Index(fields=['invoice_date', 'status'], name='admin_manag_invoice_69927b_idx'),
        ),
        migrations.AddIndex(
            model_name='membershipinvoice',
            index=models.Index(fields=['period_start', 'period_end'], name='admin_manag_period__411362_idx'),
        ),
    ]
