# Generated by Django 5.2.7 on 2026-03-22 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_management", "0002_membershipinvoice_invoicepaymentlink_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note_text", models.TextField(help_text="Content of the note")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin",
                    models.ForeignKey(
                        help_text="Admin who created this note",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        help_text="Member this note is about",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Note",
                "verbose_name_plural": "Admin Notes",
                "db_table": "admin_management_admin_notes",
                "ordering": ["-created_at"],
            },
        ),
    ]
