# Generated by Django 5.2.7 on 2026-04-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_management", "0003_adminnote"),
    ]

    operations = [
        migrations.AddField(
            model_name="suspendedmember",
            name="suspension_type",
            field=models.CharField(
                choices=[
                    ("non_payment", "Non-Payment"),
                    ("policy_violation", "Policy Violation"),
                ],
                default="non_payment",
                help_text="Type of suspension",
                max_length=20,
            ),
        ),
    ]
