# Generated by Django 5.2.7 on 2026-03-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_payment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="card_expiry",
            field=models.CharField(
                blank=True, help_text="Card expiry MM/YY", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="card_last_four",
            field=models.CharField(
                blank=True, help_text="Last 4 digits of card", max_length=4
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="cardholder_name",
            field=models.CharField(
                blank=True, help_text="Name on card", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                default=1, help_text="Payment method used", max_length=20
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_phone",
            field=models.CharField(
                blank=True, help_text="Phone number used for payment", max_length=20
            ),
        ),
    ]
