# Generated by Django 5.2.7 on 2026-03-06 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_paymentstatuscheck_webhooknotification"),
        ("payments", "0005_webhook_models"),
    ]

    operations = []
