# Generated by Django 5.2.7 on 2026-03-12 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_alter_payment_provider_paymentstatuscheck_and_more"),
        ("payments", "0006_merge_20260306_2206"),
    ]

    operations = []
