# Generated by Django 5.2.7 on 2026-03-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_merge_20260306_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice_number',
            field=models.CharField(blank=True, db_index=True, help_text='Membership renewal invoice number', max_length=50, null=True),
        ),
    ]
