# Generated by Django 5.2.7 on 2026-03-13 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_merge_20260312_2304'),
        ('payments', '0007_payment_invoice_number'),
    ]

    operations = [
    ]
