# Generated by Django 5.2.7 on 2026-03-14 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_add_manual_payment"),
        ("payments", "0008_merge_20260313_1448"),
    ]

    operations = []
