# Generated by Django 5.2.7 on 2026-03-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0009_merge_20260314_1839"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="manualpayment",
            new_name="payments_ma_status_7e97c3_idx",
            old_name="payments_man_status_b8e7c5_idx",
        ),
        migrations.RenameIndex(
            model_name="manualpayment",
            new_name="payments_ma_applica_6606f4_idx",
            old_name="payments_man_applica_4a8b9c_idx",
        ),
        migrations.AddField(
            model_name="manualpayment",
            name="description",
            field=models.CharField(
                default="Application Fee",
                help_text="Payment description (e.g., Application Fee, Renewal Fee, Event Fee)",
                max_length=200,
            ),
        ),
    ]
