# Generated by Django 5.2.7 on 2026-03-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0010_add_description_to_manual_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="manualpayment",
            name="application_reference",
            field=models.CharField(
                blank=True,
                help_text="Application ID for application-related payments (e.g., APF-2026-000123)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="manualpayment",
            name="invoice_number",
            field=models.CharField(
                blank=True,
                help_text="Invoice number for non-application payments (renewals, events, etc.)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="manualpayment",
            name="reference",
            field=models.CharField(
                help_text="Payment reference (should match Application ID or Invoice Number)",
                max_length=100,
            ),
        ),
    ]
