# Generated by Django 5.2.7 on 2026-03-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0013_renewalproofofpayment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="renewalproofofpayment",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
