# Generated by Django 5.2.7 on 2026-03-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0014_alter_renewalproofofpayment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="manualpayment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("membership_renewal", "Membership Renewal"),
                    ("donation", "Donation"),
                    ("event", "Event Payment"),
                    ("other", "Other Services"),
                ],
                default="membership_renewal",
                help_text="Type of payment (membership renewal, donation, event, other)",
                max_length=30,
            ),
        ),
    ]
