# Generated by Django 5.2.7 on 2026-03-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='sessions',
        ),
        migrations.AddField(
            model_name='event',
            name='is_paid_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Reason for rejection or verification notes'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='proof_of_payment',
            field=models.ImageField(blank=True, null=True, upload_to='event_proofs/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
