# Generated by Django 5.2.7 on 2026-03-22 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_eventregistration_sessions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='event',
        ),
        migrations.AlterModelOptions(
            name='eventregistration',
            options={'ordering': ['-created_at'], 'verbose_name': 'Event Registrations'},
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='attendance_mode',
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='event_title',
            field=models.CharField(default='', help_text='The Title of the event from Strapi', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='strapi_event_id',
            field=models.CharField(default='0', help_text='The unique ID from Strapi', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
