# Generated by Django 5.2.7 on 2026-03-22 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_eventregistration_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='event_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
