# Generated by Django 5.2.7 on 2026-03-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventregistration_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
