# Generated by Django 5.2.7 on 2026-01-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='payment_transaction_id',
        ),
        migrations.AddField(
            model_name='application',
            name='payment_error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='payment_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='idle', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='payment_transaction_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
