# Generated by Django 4.2.9 on 2026-02-07 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_add_payment_amount'),
        ('applications', '0007_relax_payment_amount_nullable'),
    ]

    operations = [
    ]
