# Generated by Django 5.2.7 on 2026-03-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0010_merge_20260210_2207"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("idle", "Idle"),
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                ],
                default="idle",
                max_length=20,
            ),
        ),
    ]
