# Generated by Django 5.2.7 on 2026-03-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0011_alter_application_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="organization",
            field=models.CharField(
                blank=True, help_text="Organization/Firm name", max_length=200
            ),
        ),
    ]
