# Generated by Django 5.2.7 on 2026-03-14 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0013_add_application_id"),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE applications_application ALTER COLUMN icpau_cert_doc DROP NOT NULL;",
            reverse_sql="ALTER TABLE applications_application ALTER COLUMN icpau_cert_doc SET NOT NULL;"
        ),
    ]
