# Generated by Django 5.2.7 on 2026-03-14 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0013_add_application_id"),
    ]

    operations = [
        migrations.RunSQL(
            """
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_name = 'applications_application'
                      AND column_name = 'icpau_cert_doc'
                ) THEN
                    ALTER TABLE applications_application
                    ALTER COLUMN icpau_cert_doc DROP NOT NULL;
                END IF;
            END $$;
            """,
            reverse_sql="""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_name = 'applications_application'
                      AND column_name = 'icpau_cert_doc'
                ) THEN
                    ALTER TABLE applications_application
                    ALTER COLUMN icpau_cert_doc SET NOT NULL;
                END IF;
            END $$;
            """,
        ),
    ]
