# Generated by Django 5.2.7 on 2026-03-14 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0014_make_icpau_cert_doc_nullable"),
    ]

    operations = [
        # First, make all existing unwanted document fields nullable to prevent errors
        migrations.RunSQL(
            """
            DO $$ 
            BEGIN
                -- Make national_id_doc nullable if it exists
                IF EXISTS (SELECT 1 FROM information_schema.columns 
                          WHERE table_name = 'applications_application' 
                          AND column_name = 'national_id_doc') THEN
                    ALTER TABLE applications_application ALTER COLUMN national_id_doc DROP NOT NULL;
                END IF;
                
                -- Make passport_doc nullable if it exists
                IF EXISTS (SELECT 1 FROM information_schema.columns 
                          WHERE table_name = 'applications_application' 
                          AND column_name = 'passport_doc') THEN
                    ALTER TABLE applications_application ALTER COLUMN passport_doc DROP NOT NULL;
                END IF;
                
                -- Add firm_license_doc if it doesn't exist
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name = 'applications_application' 
                              AND column_name = 'firm_license_doc') THEN
                    ALTER TABLE applications_application ADD COLUMN firm_license_doc VARCHAR(100);
                END IF;
                
                -- Add proof_of_payment_doc if it doesn't exist
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name = 'applications_application' 
                              AND column_name = 'proof_of_payment_doc') THEN
                    ALTER TABLE applications_application ADD COLUMN proof_of_payment_doc VARCHAR(100);
                END IF;
            END $$;
            """,
            reverse_sql="""
            ALTER TABLE applications_application DROP COLUMN IF EXISTS firm_license_doc;
            ALTER TABLE applications_application DROP COLUMN IF EXISTS proof_of_payment_doc;
            """
        ),
    ]
