# Generated by Django 5.2.7 on 2026-03-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0015_fix_document_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="firm_license_doc",
            field=models.FileField(
                blank=True,
                help_text="Firm License document",
                null=True,
                upload_to="documents/firm_licenses/",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="icpau_cert_doc",
            field=models.FileField(
                blank=True,
                help_text="ICPAU Certificate document",
                null=True,
                upload_to="documents/icpau_certs/",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="proof_of_payment_doc",
            field=models.FileField(
                blank=True,
                help_text="Proof of Payment document",
                null=True,
                upload_to="documents/payment_proofs/",
            ),
        ),
    ]
