# Generated by Django 5.2.7 on 2026-03-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0015_fix_document_fields"),
    ]

    operations = [
        migrations.RunSQL(
            """
            DO $$ 
            BEGIN
                -- Add firm_license_doc if it doesn't exist
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name = 'applications_application' 
                              AND column_name = 'firm_license_doc') THEN
                    ALTER TABLE applications_application ADD COLUMN firm_license_doc VARCHAR(100);
                END IF;
                
                -- Add icpau_cert_doc if it doesn't exist
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name = 'applications_application' 
                              AND column_name = 'icpau_cert_doc') THEN
                    ALTER TABLE applications_application ADD COLUMN icpau_cert_doc VARCHAR(100);
                END IF;
                
                -- Add proof_of_payment_doc if it doesn't exist
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name = 'applications_application' 
                              AND column_name = 'proof_of_payment_doc') THEN
                    ALTER TABLE applications_application ADD COLUMN proof_of_payment_doc VARCHAR(100);
                END IF;
            END $$;
            """,
            reverse_sql="""
            ALTER TABLE applications_application DROP COLUMN IF EXISTS firm_license_doc;
            ALTER TABLE applications_application DROP COLUMN IF EXISTS icpau_cert_doc;
            ALTER TABLE applications_application DROP COLUMN IF EXISTS proof_of_payment_doc;
            """
        ),
    ]
