# Generated by Django 5.2.7 on 2026-03-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0015_fix_document_fields"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    """
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM information_schema.columns
                            WHERE table_name = 'applications_application'
                              AND column_name = 'firm_license_doc'
                        ) THEN
                            ALTER TABLE applications_application
                            ADD COLUMN firm_license_doc VARCHAR(100);
                        END IF;

                        IF NOT EXISTS (
                            SELECT 1
                            FROM information_schema.columns
                            WHERE table_name = 'applications_application'
                              AND column_name = 'icpau_cert_doc'
                        ) THEN
                            ALTER TABLE applications_application
                            ADD COLUMN icpau_cert_doc VARCHAR(100);
                        END IF;

                        IF NOT EXISTS (
                            SELECT 1
                            FROM information_schema.columns
                            WHERE table_name = 'applications_application'
                              AND column_name = 'proof_of_payment_doc'
                        ) THEN
                            ALTER TABLE applications_application
                            ADD COLUMN proof_of_payment_doc VARCHAR(100);
                        END IF;
                    END $$;
                    """,
                    reverse_sql="""
                    ALTER TABLE applications_application
                    DROP COLUMN IF EXISTS firm_license_doc,
                    DROP COLUMN IF EXISTS icpau_cert_doc,
                    DROP COLUMN IF EXISTS proof_of_payment_doc;
                    """,
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name="application",
                    name="firm_license_doc",
                    field=models.FileField(
                        blank=True,
                        help_text="Firm License document",
                        null=True,
                        upload_to="documents/firm_licenses/",
                    ),
                ),
                migrations.AddField(
                    model_name="application",
                    name="icpau_cert_doc",
                    field=models.FileField(
                        blank=True,
                        help_text="ICPAU Certificate document",
                        null=True,
                        upload_to="documents/icpau_certs/",
                    ),
                ),
                migrations.AddField(
                    model_name="application",
                    name="proof_of_payment_doc",
                    field=models.FileField(
                        blank=True,
                        help_text="Proof of Payment document",
                        null=True,
                        upload_to="documents/payment_proofs/",
                    ),
                ),
            ],
        ),
    ]
