# Generated by Django 5.2.7 on 2026-03-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0016_application_firm_license_doc_and_more"),
    ]

    operations = [
        # This migration syncs Django's state with the database
        # The fields were already added by raw SQL in migrations 0015 and 0016
        # We use SeparateDatabaseAndState to update Django's state without touching the database
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="application",
                    name="firm_license_doc",
                    field=models.FileField(
                        blank=True,
                        help_text="Firm License document",
                        null=True,
                        upload_to="documents/firm_licenses/",
                    ),
                ),
                migrations.AddField(
                    model_name="application",
                    name="icpau_cert_doc",
                    field=models.FileField(
                        blank=True,
                        help_text="ICPAU Certificate document",
                        null=True,
                        upload_to="documents/icpau_certs/",
                    ),
                ),
                migrations.AddField(
                    model_name="application",
                    name="proof_of_payment_doc",
                    field=models.FileField(
                        blank=True,
                        help_text="Proof of Payment document",
                        null=True,
                        upload_to="documents/payment_proofs/",
                    ),
                ),
            ],
            database_operations=[
                # No database operations needed - fields already exist from raw SQL
            ],
        ),
    ]
