# Generated by Django 5.2.7 on 2026-04-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0017_sync_document_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="age_range",
            field=models.CharField(max_length=20),
        ),
    ]
