# Generated by Django 5.2.7 on 2026-03-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsmetric',
            name='metric_type',
            field=models.CharField(choices=[('count', 'Count'), ('percentage', 'Percentage'), ('average', 'Average'), ('sum', 'Sum'), ('revenue', 'Revenue'), ('ratio', 'Ratio'), ('growth_rate', 'Growth Rate')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='report_type',
            field=models.CharField(choices=[('membership', 'Membership Report'), ('applications', 'Applications Report'), ('financial', 'Financial Report'), ('events', 'Events Report'), ('revenue', 'Revenue Report'), ('compliance', 'Compliance Report'), ('growth', 'Growth Analysis Report'), ('custom', 'Custom Report')], max_length=50),
        ),
    ]
