# Generated by Django 5.2.7 on 2026-03-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_user_subscription_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_digest_frequency",
            field=models.CharField(
                choices=[("none", "None"), ("daily", "Daily"), ("weekly", "Weekly")],
                default="weekly",
                help_text="Frequency of forum activity digest emails",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="email_new_comments",
            field=models.BooleanField(
                default=True,
                help_text="Receive emails when someone comments on posts you participate in",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="email_new_posts",
            field=models.BooleanField(
                default=True, help_text="Receive emails when new posts are created"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="email_notifications_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Receive email notifications for forum activities",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="email_post_replies",
            field=models.BooleanField(
                default=True,
                help_text="Receive emails when someone replies to your posts",
            ),
        ),
    ]
