# Generated by Django 5.2.7 on 2026-03-07 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_user_address_line_1_user_address_line_2_and_more"),
        (
            "authentication",
            "0006_user_email_digest_frequency_user_email_new_comments_and_more",
        ),
    ]

    operations = []
