# Generated by Django 5.2.7 on 2026-03-09 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_merge_20260307_2324"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="user",
            name="email_notifications",
        ),
        migrations.RemoveField(
            model_name="user",
            name="event_notifications",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_profile_complete",
        ),
        migrations.RemoveField(
            model_name="user",
            name="linkedin_profile",
        ),
        migrations.RemoveField(
            model_name="user",
            name="newsletter_subscription",
        ),
        migrations.RemoveField(
            model_name="user",
            name="preferred_language",
        ),
        migrations.RemoveField(
            model_name="user",
            name="profile_picture",
        ),
        migrations.RemoveField(
            model_name="user",
            name="profile_visibility",
        ),
        migrations.RemoveField(
            model_name="user",
            name="show_email",
        ),
        migrations.RemoveField(
            model_name="user",
            name="show_phone",
        ),
        migrations.RemoveField(
            model_name="user",
            name="sms_notifications",
        ),
        migrations.RemoveField(
            model_name="user",
            name="timezone",
        ),
        migrations.RemoveField(
            model_name="user",
            name="website",
        ),
    ]
