# Generated by Django 5.2.7 on 2026-03-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0008_remove_user_bio_remove_user_email_notifications_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="User profile picture",
                null=True,
                upload_to="profile_pictures/",
            ),
        ),
    ]
