# Generated by Django 5.2.7 on 2026-04-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0010_user_account_locked_until_user_failed_login_attempts_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(
                default=False,
                help_text="True after member logs in and changes their temporary password",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="must_change_password",
            field=models.BooleanField(
                default=False,
                help_text="Forces password change on next login (set for bulk-registered members)",
            ),
        ),
    ]
