# Generated by Django 5.2.7 on 2026-06-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0011_user_email_verified_user_must_change_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="apf_membership_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="APF membership number in format APF/M/*** (assigned by admin on approval)",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
    ]
