# Generated by Django 5.2.7 on 2026-03-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_announcement"),
    ]

    operations = [
        migrations.AddField(
            model_name="usernotification",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
